package day14.test05.level2_01;

import java.io.IOException;

public  class Fu{
public void fun() throws IOException {
System.out.println("aaa");
}
}